version: '3.7'
services:
  mysql:
    image: mysql:8
    container_name: mysql-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
  php:
    container_name: php
    image: php
    tty: true
    links:
      - mysql
    ports:
      - "9005:9005"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - mysql
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - php
      - mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8181:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8
    depends_on:
      - php
      - mysql
      - nginx
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16